version: '3'

services:
  db:
    image: postgres:13.6
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - 5444:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: